### ISSUE TITLE
Character Shet refuses to allow any entries

### ISSUE THREAD

**Issue by afalk** [sparkcity/fvtt-laf#10]
Even running with all possible modules disabled the same error occurs. When you make a character - you can name them but that is it. Putting anything in the fields, immediately erases when you hit Enter or Tab to the next field.

**Comment by UsakoSenpai** [comment]
Bump. Seeing the same issue.

**Comment by The-Netherlad** [comment]
Seeing the same issue.

**Comment by BeanBagKing** [comment]
Thought it was just me, glad I found this. Anyone find a workaround?

**Comment by sonic232** [comment]
> From here, it looks like values will save, but I can't assign the character to a player? e.g I should be able to: "Once you've created an actor, you'll need to assign them to a player! Right click on an actor you've created and select "Configure Permissions." (from: https://foundryvtt.com/article/tutorial-two/). Right clicking does nothing though. I'm not sure if this is just me though, or another problem in this area.
> 

I found this problem while editing this module for one of the Lasers & Feelings hacks. Under Simple.js, under Line 116, there are a variety of functions that access 'entityId'. That property's been changed to 'documentId' (discovered through debug tools).  Changing references of 'entityId' to 'documentId' should allow you to change permissions once again and allow the context menu to appear, though I'm still testing to see if there are other reprecussions.

**Comment by UsakoSenpai** [comment]
I got around this by using the forked fix from: https://github.com/sparkcity/fvtt-laf/issues/9

**Comment by ElusiveZenith** [comment]
I created a fork, fixed everything, refactored some of the code, and updated it for Foundry 11. I plan on keeping it maintained. [link to fork](https://github.com/ElusiveZenith/fvtt-laf)

**Comment by sparkcity** [comment]
> I created a fork, fixed everything, refactored some of the code, and updated it for Foundry 11. I plan on keeping it maintained. [link to fork](https://github.com/ElusiveZenith/fvtt-laf)

Ironically had planned on scrapping the whole thing to start from scratch this weekend. I can change the Foundry link over to yours, I think.
