### ISSUE TITLE
Update to newer foundry versions

### ISSUE THREAD

**Issue by brunocalado** [sparkcity/fvtt-laf#8]
Great job.

Can you update this system for 7.10 or 0.8.x?

Tks

**Comment by RhombusWeasel** [comment]
I just did this for my game, I tried to push but I don't have permissions to push to the repo.
If you'd like the code OP let me know on here.

**Comment by ElusiveZenith** [comment]
2 years late, but I just updated it for Foundry 11 in [my fork](https://github.com/ElusiveZenith/fvtt-laf).
